command /map:
	executable by: players
	trigger:
		send "" to player
		send formatted "<dark_gray><strikethrough>                                              </strikethrough>" to player
		send formatted "<#7C9CFF><bold>POLITARIA</bold><reset> <dark_gray>»</dark_gray> <white>Карта сервера</white>" to player
		send formatted "<gray>Онлайн-карта мира:</gray>" to player
		send formatted "<click:open_url:'https://map-politaria.digitalweb.host'><#7C9CFF><bold>[ ОТКРЫТЬ КАРТУ ]</bold></click>" to player
		send formatted "<dark_gray><strikethrough>                                              </strikethrough>" to player
		send "" to player
