from pathlib import Path

path = Path('server/plugins/Skript/scripts/countries.sk')
text = path.read_text(encoding='utf-8')

anchor = '''function countryMemberRolesText(id: text, memberUuid: text) :: text:\n'''
insert = '''function countryRolePermissionCount(id: text, role: text) :: number:\n\tset {_count} to 0\n\tloop {country.role-perm::%{_id}%::%{_role}%::*}:\n\t\tif loop-value is true:\n\t\t\tadd 1 to {_count}\n\treturn {_count}\n\nfunction countryMemberMainRole(id: text, memberUuid: text) :: text:\n\tif {country.owner::%{_id}%} is {_memberUuid}:\n\t\treturn "owner"\n\tcountryEnsureRoleStorage({_id}, {_memberUuid})\n\tset {_best-role} to ""\n\tset {_best-rights} to -1\n\tloop {country.roles-of::%{_id}%::%{_memberUuid}%::*}:\n\t\tif loop-value is true:\n\t\t\tset {_role} to loop-index\n\t\t\tset {_rights} to countryRolePermissionCount({_id}, {_role})\n\t\t\tif {_rights} is greater than {_best-rights}:\n\t\t\t\tset {_best-rights} to {_rights}\n\t\t\t\tset {_best-role} to {_role}\n\tif {_best-role} is "":\n\t\tif {country.role-name::%{_id}%::citizen} is set:\n\t\t\treturn "citizen"\n\treturn {_best-role}\n\nfunction countryMemberRoleIcon(id: text, memberUuid: text) :: item type:\n\tset {_role} to countryMemberMainRole({_id}, {_memberUuid})\n\tif {_role} is "owner":\n\t\treturn nether star\n\tif {_role} is not "":\n\t\tset {_type} to {country.role-icon::%{_id}%::%{_role}%} parsed as item type\n\t\tif {_type} is set:\n\t\t\treturn {_type}\n\treturn paper\n\nfunction countryMemberMainRoleName(id: text, memberUuid: text) :: text:\n\tset {_role} to countryMemberMainRole({_id}, {_memberUuid})\n\tif {_role} is "owner":\n\t\treturn "Правитель"\n\tif {_role} is not "":\n\t\treturn countryRoleName({_id}, {_role})\n\treturn "Гражданин"\n\n'''
if 'function countryMemberMainRole(' not in text:
    idx = text.index(anchor)
    text = text[:idx] + insert + text[idx:]

old_list = '''\t\tset {_roles-text} to countryMemberRolesText({_id}, {_member-uuid})\n\t\tset {_member-head} to player head\n\t\tset {_online-member} to player({_member-uuid}, true)\n\t\tif {_online-member} is set:\n\t\t\tset {_loaded-head} to head of {_online-member}\n\t\t\tif {_loaded-head} is set:\n\t\t\t\tset {_member-head} to {_loaded-head}\n\t\telse:\n\t\t\tset {_member-profile} to offlineplayer({_member-name}, true)\n\t\t\tif {_member-profile} is set:\n\t\t\t\tset {_loaded-head} to head of {_member-profile}\n\t\t\t\tif {_loaded-head} is set:\n\t\t\t\t\tset {_member-head} to {_loaded-head}\n\t\tset name of {_member-head} to "<white><bold>%{_member-name}%"\n\t\tset lore of {_member-head} to "<gray>Роли: <white>%{_roles-text}%" and "" and "<yellow>Нажмите для управления"\n\t\tset slot {_slot} of {_menu} to {_member-head}\n'''
new_list = '''\t\tset {_roles-text} to countryMemberRolesText({_id}, {_member-uuid})\n\t\tset {_main-role} to countryMemberMainRole({_id}, {_member-uuid})\n\t\tset {_main-role-name} to countryMemberMainRoleName({_id}, {_member-uuid})\n\t\tset {_member-icon} to countryMemberRoleIcon({_id}, {_member-uuid})\n\t\tif {_main-role} is "owner":\n\t\t\tset {_rights-text} to "Все права"\n\t\telse:\n\t\t\tset {_rights} to countryRolePermissionCount({_id}, {_main-role})\n\t\t\tset {_rights-text} to "%{_rights}% прав"\n\t\tset {_member-item} to {_member-icon} named "<white><bold>%{_member-name}%" with lore "<gray>Главная роль: <white>%{_main-role-name}%" and "<gray>Права роли: <white>%{_rights-text}%" and "<gray>Все роли: <white>%{_roles-text}%" and "" and "<yellow>Нажмите для управления"\n\t\tset slot {_slot} of {_menu} to {_member-item}\n'''
if old_list not in text:
    raise SystemExit('member list block not found')
text = text.replace(old_list, new_list, 1)

old_detail = '''\tset {_member-head} to player head\n\tset {_online-member} to player({_memberUuid}, true)\n\tif {_online-member} is set:\n\t\tset {_loaded-head} to head of {_online-member}\n\t\tif {_loaded-head} is set:\n\t\t\tset {_member-head} to {_loaded-head}\n\telse:\n\t\tset {_member-profile} to offlineplayer({_name}, true)\n\t\tif {_member-profile} is set:\n\t\t\tset {_loaded-head} to head of {_member-profile}\n\t\t\tif {_loaded-head} is set:\n\t\t\t\tset {_member-head} to {_loaded-head}\n\tset name of {_member-head} to "<white><bold>%{_name}%"\n\tset lore of {_member-head} to "<gray>Роли: <white>%{_roles-text}%"\n\tset slot 4 of {_menu} to {_member-head}\n'''
new_detail = '''\tset {_main-role} to countryMemberMainRole({_id}, {_memberUuid})\n\tset {_main-role-name} to countryMemberMainRoleName({_id}, {_memberUuid})\n\tset {_member-icon} to countryMemberRoleIcon({_id}, {_memberUuid})\n\tif {_main-role} is "owner":\n\t\tset {_rights-text} to "Все права"\n\telse:\n\t\tset {_rights} to countryRolePermissionCount({_id}, {_main-role})\n\t\tset {_rights-text} to "%{_rights}% прав"\n\tset {_member-item} to {_member-icon} named "<white><bold>%{_name}%" with lore "<gray>Главная роль: <white>%{_main-role-name}%" and "<gray>Права роли: <white>%{_rights-text}%" and "<gray>Все роли: <white>%{_roles-text}%"\n\tset slot 4 of {_menu} to {_member-item}\n'''
if old_detail not in text:
    raise SystemExit('member detail block not found')
text = text.replace(old_detail, new_detail, 1)

path.write_text(text, encoding='utf-8')
print('Replaced member heads with highest-permission role icons.')
