name: PolitariaApartments
version: 1.0.0
main: ru.politaria.apartments.ApartmentPlugin
api-version: '1.21'
depend: [Skript]
loadbefore: [PolitariaIdentity]
commands:
  apartments:
    description: Список квартир страны
    aliases: [flats, квартиры]
  apartment:
    description: Управление своей квартирой
    aliases: [apt, квартира]
permissions:
  politaria.apartments.admin:
    default: op
  politaria.apartment.event.build:
    default: false
  politaria.apartment.event.interact:
    default: false
