name: PolitariaLocator
version: '${version}'
main: io.politaria.locator.PolitariaLocator
api-version: '1.21'
authors: [washaps0]
description: Shows only citizens of the same Politaria country on the vanilla Locator Bar.
depend: [ProtocolLib, Skript]

commands:
  politarialocator:
    description: Reload PolitariaLocator configuration.
    usage: /politarialocator
    permission: politaria.locator.admin

permissions:
  politaria.locator.admin:
    description: Allows reloading PolitariaLocator.
    default: op
