plugins { id 'java' }
group = 'ru.politaria'
version = '1.0.0'
def serverDirectory = file('../..')
dependencies {
    compileOnly files(new File(System.getProperty('user.home'), '.m2/repository/io/papermc/paper/paper-api/1.21.1-R0.1-SNAPSHOT/paper-api-1.21.1-R0.1-SNAPSHOT.jar'))
    compileOnly fileTree(new File(serverDirectory, 'plugins')) { include 'Skript*.jar' }
    compileOnly fileTree(new File(serverDirectory, 'libraries')) { include '**/*.jar' }
}
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-proc:none')
}
jar { archiveFileName = 'PolitariaApartments.jar' }
