#Minecraft server properties
#Thu Sep 10 10:30:14 EDT 2026
accepts-transfers=true
allow-flight=true
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
compression-threshold=64
debug=false
difficulty=normal
enable-command-block=false
enable-jmx-monitoring=false
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=50
max-tick-time=60000
max-world-size=29999984
motd=§l §9              Politaria§6 [ §l§n1.16.5§6 - §l§n 26.2 ]§r\n§l  §6           §9§lСамый лучший сервер\!
network-compression-threshold=64
online-mode=false
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.enabled=true
query.port=12328
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=0.0.0.0
server-name=Politaria
server-port=12328
server-portv6=0
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=50
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=10
white-list=false
