plugins { id 'java' }

group = 'ru.politaria'
version = '1.0.0'

def serverDirectory = file('../..')

repositories {
    maven { url = uri('https://repo.papermc.io/repository/maven-public/') }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly files(new File(serverDirectory, 'plugins/SkinsRestorer.jar'))
}

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-proc:none')
}

jar { archiveFileName = 'PolitariaSkinHeads.jar' }
